### ISSUE TITLE
clean out invalid PDF/XML files?

### ISSUE THREAD

**Issue by sckott** [ropensci/fulltext#142]
Fxn to help users remove PDF/XML files that are invalid. Not sure if this is easy to do or not. 

- For PDFs attempt to extract metadata, and if it's all borked, then likely not a pdf
- For XML, maybe read it in, and check if it's valid XML
- Would be hard to know for sure to remove a file if it was e.g., valid XML, but with an error message in it saying something like "you're not authorized", which elsevier does i know

**Comment by sckott** [comment]
thanks for the bump @lucymerobinson - will have a look

**Comment by sckott** [comment]
@lucymerobinson can you reinstall `remotes::install_github("ropensci/fulltext@cache-clean")` and see new fxn `cache_file_info`

let me know what you think

**Comment by lucymerobinson** [comment]
thanks @sckott the issue is with the NULL value that is returned from ft_collect when the xml isn't downloaded into my cache path after using ft_get on the search results returned from ft_search (because I don't have permission or there was an error - according to the warning that scopus provide). So after using ft_collect on the ft object that is created from using ft_get I can work around this by using for example text_data$elsevier$data$data[sapply(text_data$elsevier$data$data, is.null)] <- NULL and this will only include documents that were downloaded if that makes sense? I was also wondering if it is possible to create an ft class object from the xml files that are stored in your cache path? At present it seems like you have to use ft_search to use ft_get and then ft_collect, but I am probably missing something.

**Comment by sckott** [comment]
did the new function `cache_file_info` seem useful at all?

> the issue is with the NULL value that is returned from ft_collect when the xml isn't downloaded into my cache path after using ft_get 

a reproducible eg would be great! if you can share one

> I was wondering if it is possible to create an ft class object from the xml files that are stored ... 

no, not at the moment. I can look into that

**Comment by sckott** [comment]
@lucymerobinson opened separate issue for the 2nd thing https://github.com/ropensci/fulltext/issues/172

**Comment by lucymerobinson** [comment]
Here is an e.g. to demonstrate the issue 
search_articles <- ft_search(query = 'TITLE-ABS-KEY(ecology)',from = 'scopus', scopusopts = list(key = Sys.getenv('ELSEVIER_SCOPUS_KEY')), limit = 100)

text_articles <- ft_get(search_articles$scopus$data$`prism:doi`,from = "elsevier")

text_new <- text_articles %>% ft_collect() 

# everything works up until this point and then when I attempt to extract abstract text from the xml files 
text_test <- text_new %>% ft_chunks(what = "abstract") %>% ft_tabularize()

# I get the following error: 
# Error in UseMethod("read_xml") : 
#   no applicable method for 'read_xml' applied to an object of class "NULL" 

# So 35 of the xml docs stored in the ft object were not downloaded into my cache file because I did not have access or an error occurred 
# e.g. 
# Warning message x 35
#   1: you may not have access to 10.1007/978-3-319-95588-9_6 or an error occurred

# But these files/articles are still stored in the ft object #i.e. 
table(sapply(text_new$elsevier$data$data, is.null))
# FALSE  TRUE 
# 65    35

# So if these NULL docs are cleared out using 
text_new$elsevier$data$data[sapply(text_new$elsevier$data$data, is.null)] <- NULL

# then it works
text_test_new <- text_new %>% ft_chunks(what = "abstract") %>% ft_tabularize()

# But I wondered if was worth storing those NULL docs that don't download...this is probably a different issue to the invalid pdf or xml files that do download so happy for you to shift it if its misleading in here.

**Comment by sckott** [comment]
@lucymerobinson can you rerun your example above, then run `traceback()` and paste in the output here when you run into that error 

```r
#> Error in UseMethod("read_xml") :
#> no applicable method for 'read_xml' applied to an object of class "NULL"
```

which should give us where that error occurs. 

I can't seem to replicate your problem, even withouth my VPN turned on for UC berkeley. 

it's also worth installing latest version as I may have fixed something related to this.

**Comment by sckott** [comment]
any thoughts @lucymerobinson ?

**Comment by lucymerobinson** [comment]
Thanks @sckott. Just tested this and there is no more error anymore so it seems to be fixed.

**Comment by sckott** [comment]
great, thanks @lucymerobinson !
