### ISSUE TITLE
ft_get_si file type

### ISSUE THREAD

**Issue by sckott** [ropensci/fulltext#69]
Hi again @willpearse 

Curious if output of `ft_get_si()` might be slightly more helpful to users if it contained some information about file type. 

Looks like at least in one example, figshare, the plugin does get the file name and has the file extension in it:

```r
.grep.url(paste0("http://dx.doi.org/", doi), "(http://files\\.figshare\\.com/)[-a-zA-Z0-9\\_/\\.]*", si)
#> [1] "http://files.figshare.com/1441270/sampling_curve.csv"
```

Where we could get file type from that. 

If we have file type, could add it as an attribute

```r
xx <- tempfile()
attr(xx, "type") <- "csv"
xx
#> [1] "/var/folders/gs/4khph0xs0436gmd2gdnwsg080000gn/T//Rtmp8JHVqv/file5ec1628ad2c0"
#> attr(,"type")
#> [1] "csv"
```

Or create a lightweight S3 class with file type and a class name, then you could dispatch on that object in various ways. 

Thoughts?

**Comment by willpearse** [comment]
I think using attributes is a good idea: it would be simple to do, and I think you're right it would be useful.

I'd be somewhat concerned about making a class and then having some sort of dispatch, because by returning a plain ```character``` the output can be used in anything that loads a file. I'm not convinced it would reliably do that if we did something more complex; I could be convinced, of course!

Since everything uses caching by default, a user can quite easily get the file type out if we have an attribute - the second time they run the line it should return almost immediately. So it shouldn't be too much of a burden to ask them to just run the function once to see what they get, and then pop it inside a ```read.csv``` or something.

Does that sound OK? By all means assign it to me; I'm happy to do this on my next 'Friday fulltext' session :p

**Comment by sckott** [comment]
I think you're right that simply adding an attribute is best. Thanks again :+1:

**Comment by sckott** [comment]
i think you have to be a collaborator to assign you, added you to a team for this repo

**Comment by willpearse** [comment]
Great, thanks!

**Comment by sckott** [comment]
@willpearse I think this is sorted now, right?

**Comment by willpearse** [comment]
Yep! Thanks Scott!

**Comment by sckott** [comment]
cool, thx
