### ISSUE TITLE
Use case: Create overview visualizations based on full text similarities on the fly

### ISSUE THREAD

**Issue by pkraker** [ropensci/fulltext#75]
I would like to use your package to create overview visualizations using full text similarities for different sources on the fly. I have implemented a prototype for PLOS using the rplos package here: http://openknowledgemaps.org/mozfest/ (source repo: http://github.com/pkraker/Headstart)

Speed is key in this use case. Experimenting with rplos, I found that the fastest way to do this is to get the field "everything" (article plain text) via searchplos.

**Comment by sckott** [comment]
Good idea, and nice app :)

PLOS will likely be the fastest as one can get full text, or any part of a paper, directly from their Solr engine (as you have done), whereas with I think all others we need to download either XML, PDF, or plain text, parse it, then return the text. And extracting text from PDFs will be the slowest I imagine. For speed reasons, using PLOS for your app seems best, esp if e.g., you just want to pull down abstracts, or just introductions, for example.

Do you want to have users do searchers by publisher, or across publishers?  

I imagine you want to stick to open access content? I'm working on making auth easy for non OA content, but it's not really ready yet

I imagine you'd probably want to stick to XML, rather than PDF, so you don't have to wait the extra time for text to be extracted from PDFs

Having a low-ish default limit (users could toggle) would at least allow the initial visualization to appear faster. But perhaps I don't understand what your needs are for sample size

**Comment by pkraker** [comment]
Thanks for your feedback :+1: As for Solr vs. XML vs. PDF: I will have to try. I guess it depends on the end result whether the user will be willing to wait for, say, 2 or 3 minutes. But I had hoped that some other providers adopted the Solr approach by PLOS.

> Do you want to have users do searchers by publisher, or across publishers?

Ideally, it would work across publishers. The best bets for that are probably Crossref and Pubmed (within the disciplines that Pubmed serves). These two are next on my list, unless you have any other suggestions.

> I imagine you want to stick to open access content? I'm working on making auth easy for non OA content, but it's not really ready yet

Yes, definitely want to stick to OA content right now.

**Comment by sckott** [comment]
> But I had hoped that some other providers adopted the Solr approach by PLOS.

not that I know of. That brings up a good opportunity for a 3rd party to grab OA articles, and allow users to grab sections of articles to make mining faster. Don't know of anyone doing it though. 

> The best bets for that are probably Crossref and Pubmed (within the disciplines that Pubmed serves). These two are next on my list, unless you have any other suggestions.

Good idea, Entrez, via the `rentrez` package used in this package gives access to pubmed. Crossref is just used for search, so to get full text you need to download from each publisher, but you can filter to get only OA papers from Crossref. Pensoft is a another good one, they are all OA and provide XML

> want to stick to OA content right now.

that's good, even when auth is incorporated for paywalled stuff, it will still be relatively painful to navigate
